# Generated by Django 5.2.4 on 2025-10-03 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='min_tickets',
            field=models.PositiveIntegerField(default=0, help_text='Minimum previous tickets required'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_total_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum previous spending required', max_digits=8),
        ),
        migrations.AddField(
            model_name='promocode',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promocode',
            name='seat_type',
            field=models.CharField(choices=[('ALL', 'All seats'), ('VIP', 'VIP only'), ('REGULAR', 'Regular only')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='promocode',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='promocodes', to='cinema.moviesession'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max uses globally (null = unlimited)', null=True),
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='cinema.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('promo', 'user')},
            },
        ),
    ]
