# Generated by Django 5.2.4 on 2025-10-05 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_promocode_min_tickets_promocode_min_total_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='movie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='cinema.movie'),
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='sessions',
        ),
        migrations.AddField(
            model_name='promocode',
            name='sessions',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='cinema.moviesession'),
        ),
    ]
