# Generated by Django 5.2.4 on 2025-10-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_venueplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueplan',
            name='site_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
