# Generated by Django 5.2.4 on 2026-01-23 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_created_at'),
        ('api', '0004_alter_venueplan_site_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewEventLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('tickets_sold', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload event image', null=True, upload_to='event_image')),
                ('organizer_id', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Event Location (view)',
                'verbose_name_plural': 'Event Locations (view)',
                'db_table': 'view_future_event_locations',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='tier_type',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='EventSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventSite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eventSite',
            },
        ),
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventPlan', to='api.eventsite')),
            ],
            options={
                'db_table': 'eventPlan',
            },
        ),
        migrations.CreateModel(
            name='EventSiteLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventSite_locations', to='api.eventsite')),
            ],
            options={
                'db_table': 'eventSite_locations',
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcmtoken', models.TextField(unique=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to='accounts.customer')),
            ],
            options={
                'db_table': 'user_fcmToken',
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
            options={
                'db_table': 'event_locations',
                'unique_together': {('event', 'location_name')},
            },
        ),
    ]
