# Generated by Django 5.2.4 on 2026-03-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restocategory_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('POPCORN', 'Popcorn'), ('DRINKS', 'Boissons'), ('CANDIES', 'Bonbons'), ('SNACKS', 'Snacks'), ('COMBO', 'Menus combo')], default=None, max_length=20),
        ),
        migrations.DeleteModel(
            name='RestoCategory',
        ),
    ]
