# Generated by Django 5.2.4 on 2026-03-19 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_fooditem_category_delete_restocategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_ticket_price',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='event',
            name='owner_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of ticket price that goes to the app owner (min 1%).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Event approval status', max_length=20),
        ),
    ]
