# Generated by Django 5.2.4 on 2025-09-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Organizer', 'organizer'), ('Event_organizer', 'event_organizer')], default='organizer', max_length=20),
        ),
    ]
