# Generated by Django 5.2.4 on 2026-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
