# Generated by Django 5.2.4 on 2026-03-27 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_is_deleted_deletedaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_content', models.CharField(blank=True, max_length=255, null=True)),
                ('notif_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for_admin', to=settings.AUTH_USER_MODEL)),
                ('notif_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_is_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
