# Generated by Django 5.2.4 on 2026-03-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_notifications_notif_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='target_id',
            field=models.IntegerField(default=0),
        ),
    ]
