
from django.urls import path
from . import views
from .views import (
  EventListView, 
  EventDetailView,
  MyTicketsAPIView, 
  BuyTicketView, 
  TicketListView, 
  TicketDeleteView, 
  HomeEventListView, 
  ValidateTicketView,
  PreviewTicketView, 
  LikeEventView, 
  RateEventView, 
  UsedTicketsAPIView,
  VenuePlanInsertView,
  VenuPlanView,
  VenuePlanDeleteView,
  VenuePlanUpdateView
)
urlpatterns = [
    path('test-get-all-events/', views.test_get_all_events, name='test_get_all_events'),
      path('hello/', views.hello_world),
  path('getAllTicket', views.getAllTicket, name='getAllTicket'),
  path('add_event/', views.add_addEvent, name='add_event'),
  path('all_event/', views.getAllEvent, name='all_event'),
  path('update_event/<int:id>/', views.updateEvent, name='update_event'),
  path('delete_event/<int:id>/', views.delete_event, name='delete_event'),
  path('add_image_and_price/<int:id_event>/', views.add_image_and_price, name='add_image_and_price'),
  path('update_image_and_price/<int:id_event>/', views.update_image_and_price, name='update_image_and_price'),
  path('all_ticket/', TicketListView.as_view(), name='all_ticket'),
  path('delete_ticket/<int:ticket_id>/', TicketDeleteView.as_view(), name='delete_ticket'),
  path('venue_plan/', VenuePlanInsertView.as_view(), name='venue_plan'),
  path('event_site_locations/', views.EventSiteLocationsInsertView.as_view(), name='event_site_locations'),
  path('event_plan/<str:site_name>/', views.EventPlanView.as_view(), name='event_plan_per_site'),
  path('event_site/', views.EventSiteView.as_view(), name='event_site'),
  path('venue_plan_view/', VenuPlanView.as_view(), name='venue_plan_view'),
  path('event_plan/', views.EventPlanView.as_view(), name='event_plan'),
  path('new/event_plan/',views.EventPlanNewInsertion.as_view(),name='new_event_plan'),
  path('future/event-locations/', views.FutureEventLocationListAPIView.as_view(), name='future-event-locations'),
  path('organizer/plan/<int:org_id>/', views.SelectedOragnizerEventPlanView.as_view(), name='organizer_plan'),
  path('mvola/initPayment/',views.MvolaView.as_view(),name='mvola_init_payment'),
  path('eventLocation/',views.EventlocationView.as_view(),name='event-location'),
  # path("mvola/callback/", views.MvolaCallbackView.as_view(), name="mvola-callback"),
  path("save-fcm-token/", views.RegisterFCMToken.as_view(), name="save_fcm_token"),
  path("mvola/callback/", views.mvola_callback, name="mvola-callback"),
  # path('fcmtoken/', views.FCMTokenView.as_view(), name='register-fcm-token'),
  # path()
  path('delete_venue/<int:pk>/', VenuePlanDeleteView.as_view(), name='venue_plan'),
  path('venue_plan_update/<int:pk>/', VenuePlanUpdateView.as_view(), name='venue-plan-update'),
  path('organizer_event/<int:creator>/', views.OrganizerEventsView.as_view(), name='organizer_event'),

    # mobile app urls
  path('mobile/new/event_plan/',views.EventPlanNewInsertionCustomer.as_view(),name='new_event_plan'),
  path('mobile/event/likes',views.MobileEventLikes.as_view(),name='event-likes'),
  path('mobile/events/', EventListView.as_view(), name='api-events'),
    path('mobile/events/<int:pk>/', EventDetailView.as_view(), name='api-event-detail'),
    path('mobile/my-tickets/', MyTicketsAPIView.as_view(), name='my-tickets'),
    path('mobile/buy-ticket/', BuyTicketView.as_view(), name='buy-ticket'),
    path('mobile/home-events/', HomeEventListView.as_view(), name='api-home-events'),
    path('mobile/preview-ticket/', PreviewTicketView.as_view(), name='preview-ticket'),
    path('mobile/validate-ticket/', ValidateTicketView.as_view(), name='validate-ticket'),
    path('mobile/like-event/<int:event_id>/', LikeEventView.as_view(), name='like-event'),
    path('mobile/rate-event/<int:event_id>/', RateEventView.as_view(), name='rate-event'),
    path('mobile/used-tickets/', UsedTicketsAPIView.as_view(), name='used-tickets'),
    path('mobile/event/<int:event_id>/price-tiers/', views.EventPriceTiersView.as_view(), name='event-price-tiers'),
    path('mobile/venue-plans/', views.CustomerVenuePlansView.as_view(), name='customer-venue-plans'),
    path('mobile/event_plans/', views.MobileEventPlansView.as_view(), name='mobile_event_plans'),
    path('mobile/tickets/seat-ids/<int:event_id>/', views.MobileSeatIdsByEventAPIView.as_view(), name='mobile-seat-ids-by-event')
]
